### ISSUE TITLE
Enable conversion out of _notebooks with free destination

### ISSUE THREAD

**Issue by A-Alaa** [fastai/fastpages#34]
Add an option to consider all notebooks that are not necessarily in the `_notebooks`. This can be useful for static generators other than Jekyll.

The option can be add initially as following:

```yaml
inputs:
  ...
  BOOL_FREE_STRUCTURE:
    description: Either 'true' or 'false'.  Whether or not to consider all notebooks which are not necessarily located in _notebooks dir to be converted. If set to 'true' the generated markdown files will be located in the same source directory. This is useful for static website generators other than Jekyll.
    required: false
    default: false
```
