### ISSUE TITLE
Privately hosted blog

### ISSUE THREAD

**Issue by lucasvw** [fastai/fastpages#345]
Hi,

Im looking into a solution to have a fastpages-like solution to share data insights at the company Im working through jupyter notebooks.

We have our infrastructure on Google Cloud, so I was kind of hoping for a way to make the Github Actions to be able to publish the blog in some Google Cloud Storage bucket.

That would allow for the blog to be only accesible by people from the company through SSO.

Any ideas on how this could be achieved? Or other ideas on how to create a privately hosted blog?

**Comment by lucasvw** [comment]
I think I got it,

by using 

```
- uses: actions-hub/gcloud@master
  env:
    PROJECT_ID: test
    APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  with:
    args: cp your-file.txt gs://your-bucket/
    cli: gsutil
```
from [https://github.com/actions-hub/gcloud](https://github.com/actions-hub/gcloud)

instead of the

```
- name: Deploy
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_dir: ./_site
```

this should probably be possible, right?

So perhaps something like

```
- name: Deploy
      if: github.event_name == 'push'
      uses: actions-hub/gcloud@master
      env:
          PROJECT_ID: test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
          args: cp -r ./_site gs://your-bucket/
          cli: gsutil
```
