### ISSUE TITLE
Add an option to bypass the Jekyll blog naming convention (no date restriction)

### ISSUE THREAD

**Issue by A-Alaa** [fastai/fastpages#35]
Add an option to enable using custom filenames without forcing the addition of the date as prefix. This can be useful for other static website generators.

Initially the option can be added as following:

```yaml
inputs:
  ...
  BOOL_FORCE_DATE:
    description: Either 'true' or 'false'.  Whether or not to force the date prefix for the markdown generated files from the notebooks.
    required: false
    default: true
```
