### ISSUE TITLE
Change branch name from master to main.

### ISSUE THREAD

**Issue by goodboychan** [fastai/fastpages#365]
**Is your feature request related to a problem? Please describe.**
Due to the change of branch naming in github, it is required to change default branch name from `master` to `main` (or specific name). Currently, annotation is shown while triggering github actions.

**Describe the solution you'd like**
I manually changed my default branch name, and edit ci.yaml to trigger gh-pages.
 - Change my branch name through console
```bash
git branch -m master main
git push -u origin main
```
- Change default branch through github setting (master -> main)
- edit ci.yaml
```
...
name: CI
on:
  push:
    branches:
      - **main** # need to filter here so we only deploy when there is a push to master
  # no filters on pull requests, so intentionally left blank
  pull_request: 
...

    - name: Copy Repository Contents
      uses: actions/checkout@**main**
      with:
        persist-credentials: false

...
```

Is there any way to change it automatically? 

Thanks.
