### ISSUE TITLE
Automatic centering of Altair charts/tables?

### ISSUE THREAD

**Issue by kai-tub** [fastai/fastpages#437]
First of all,
Thank you so much for this awesome tool! 👍 

I love it! It helped me so much, just to start blogging without having to reinvent the wheel.
I have little knowledge about web development, so please excuse me if I am missing a simple fix.

I really like that the images included with ! []() are automatically centered.
To keep the style consistent I would like to center all "objects", such as tables and charts.

I assume I could change the styling of the tables with CSS styling or use HTML tables and style them manually.
But I have no idea how one would go about centering Altair charts. 
The charts are the output of the cell and I don't know if it is even possible to center the cell output?

I would like to keep the charts interactive, so saving as an image is not an option.
Am I missing something?

Thanks!

**Comment by hamelsmu** [comment]
I don't think this is possible at the moment.  What about resizing the chart to make it fill the space?

**Comment by kai-tub** [comment]
Resizing to fill up the screen results in too wide charts for mobile.
In case someone wants to see my noob CSS solution:
I've added the following lines to the `custom-styles.scss` folder:
```css
[id^=altair-viz] {
  text-align: center;
  display: flex !important;
  justify-content: center;
  align-items: center;
}
``` 
This should center all resulting Altair charts. I tried to find a _nice_ solution for tables too but I couldn't find a satisfying solution
```css
table {
  display: block !important;
  white-space: normal;
  max-width: 100%;
  // Increase the font size to 100%
  font-size: 100%;
  border:none;
  th{
    text-align: center! important;
  }
  width: 90%;
  margin-left: 5%;
  margin-right: 5%;
}
```
I couldn't get it to work with `auto`...

Maybe this helps somebody. :)
