### ISSUE TITLE
Code in markdown doesn't follow Dracula theme

### ISSUE THREAD

**Issue by daniel-dewitt** [fastai/fastpages#473]
I was looking at the **fastpages-dracula-highlight.scss** file as a template for creating my own custom syntax highlighter when I noticed the following code:
```css
// ensure dark background for code in markdown
[class^="language-"]:not(.language-plaintext) pre,
[class^="language-"]:not(.language-plaintext) code {
    background-color: $dt-code-cell-background !important;
    color: $dt-gray-light;
}
```

I don't believe this is working as intended. I was unable to get the code-in-markdown to change from the original theme on my own copy of the repo, even when specifying hex codes directly instead of using **$dt-code-cell-background** and **$dt-grey-light**. Furthermore, it looks like the code-in-markdown still has the default theming on the demo site as well: https://fastpages.fast.ai/jupyter/2020/02/20/test.html#Front-Matter
