### ISSUE TITLE
Issue when using templating in code blocks

### ISSUE THREAD

**Issue by fbraza** [fastai/fastpages#569]
Hi maintainers,

I am having the following issue. Every pieces of code between `{{}}` disappear (including the brackets) after the formatting and deployment of an article with `fastpages`. I understood that `fastpages` uses some templating like for example to render images with `{{site.baseurl}}`. But I have the feeling that the algorithm is trying to run or harness any types of templating which leads to some issues. More specifically, look at this code
 
```yaml
name: CI Pipeline for summarize_df
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Test with tox
      run: poetry run tox
```
And look how it is rendered in this article [here](https://github.com/fbraza/BrazLog/blob/master/images/screenshot.png)

Do you have an idea how to circumvent this problem?

Many thanks

Faouzi
