### ISSUE TITLE
Provide users with a path to automated upgrade

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#77]
- merges upstream master into their repo on a new branch
- open a PR
- user has to fix conflicts?

@jph00 can you think of a nice workflow where people should upgrade?  Is git merge/fix conflicts the best route, you think?

**Comment by jph00** [comment]
Yes I suspect that's the best approach.

**Comment by mikonapoli** [comment]
I have actually built a GitHub action that does something similar on a different project. I use git-subtree to keep a folder in sync with my upstream, but probably can be easily adapted to this use case. 
If it's useful, the relevant part of the action I am using is:

```yaml
jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: master
          fetch-depth: 0
    - name: Set git user and email
      uses: srt32/git-actions@master
      with:
        args: git config user.email "upstreamsyncbot@example.com" && git config user.name "UpstreamSyncBot"
    - name: Fetch upstream repo
      uses: srt32/git-actions@master
      with:
        args: git subtree pull --squash --message=UpstreamSync  --prefix=base-images https://github.com/upstream-github-user/upstream-repo.git master
```
Most likely it is overkill with what's needed here
